#!/bin/bash
# Interactive script to set up environment variables for production
# Run this script as root or with sudo

set -e  # Exit on error

echo "========================================="
echo "Environment Variables Setup"
echo "========================================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

ENV_FILE="/opt/hostaway-messages/.env"
ENV_EXAMPLE="deployment/.env.production.example"

# Check if .env.example exists
if [ ! -f "$ENV_EXAMPLE" ]; then
    echo -e "${RED}Error: $ENV_EXAMPLE not found${NC}"
    echo "Please run this script from the project root directory"
    exit 1
fi

# Generate a secure SECRET_KEY if not provided
generate_secret_key() {
    python3 -c "import secrets; print(secrets.token_hex(32))"
}

echo -e "${GREEN}Setting up environment variables...${NC}"
echo ""

# Read existing .env if it exists
if [ -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}Existing .env file found. Values will be prompted.${NC}"
    echo -e "${YELLOW}Press Enter to keep existing value or type new value.${NC}"
    echo ""
    # Source existing values
    set -a
    source "$ENV_FILE" 2>/dev/null || true
    set +a
fi

# Prompt for required variables
echo -e "${GREEN}Required Variables:${NC}"
echo ""

# DATABASE_URL
if [ -z "$DATABASE_URL" ]; then
    read -p "DATABASE_URL (postgresql://user:password@localhost:5432/hostaway_prod): " DATABASE_URL
else
    read -p "DATABASE_URL [current: $DATABASE_URL]: " NEW_DATABASE_URL
    DATABASE_URL=${NEW_DATABASE_URL:-$DATABASE_URL}
fi

# SECRET_KEY
if [ -z "$SECRET_KEY" ]; then
    read -p "SECRET_KEY (press Enter to generate): " SECRET_KEY
    if [ -z "$SECRET_KEY" ]; then
        SECRET_KEY=$(generate_secret_key)
        echo -e "${GREEN}Generated SECRET_KEY${NC}"
    fi
else
    read -p "SECRET_KEY [current: (hidden)] (press Enter to keep, or type new): " NEW_SECRET_KEY
    SECRET_KEY=${NEW_SECRET_KEY:-$SECRET_KEY}
fi

# OPENAI_API_KEY
if [ -z "$OPENAI_API_KEY" ]; then
    read -p "OPENAI_API_KEY: " OPENAI_API_KEY
else
    read -p "OPENAI_API_KEY [current: (hidden)] (press Enter to keep, or type new): " NEW_OPENAI_API_KEY
    OPENAI_API_KEY=${NEW_OPENAI_API_KEY:-$OPENAI_API_KEY}
fi

# HOSTAWAY_ACCOUNT_ID
if [ -z "$HOSTAWAY_ACCOUNT_ID" ]; then
    read -p "HOSTAWAY_ACCOUNT_ID (optional, for sync operations): " HOSTAWAY_ACCOUNT_ID
else
    read -p "HOSTAWAY_ACCOUNT_ID [current: $HOSTAWAY_ACCOUNT_ID]: " NEW_HOSTAWAY_ACCOUNT_ID
    HOSTAWAY_ACCOUNT_ID=${NEW_HOSTAWAY_ACCOUNT_ID:-$HOSTAWAY_ACCOUNT_ID}
fi

# HOSTAWAY_API_KEY
if [ -z "$HOSTAWAY_API_KEY" ]; then
    read -p "HOSTAWAY_API_KEY (optional, for sync operations): " HOSTAWAY_API_KEY
else
    read -p "HOSTAWAY_API_KEY [current: (hidden)] (press Enter to keep, or type new): " NEW_HOSTAWAY_API_KEY
    HOSTAWAY_API_KEY=${NEW_HOSTAWAY_API_KEY:-$HOSTAWAY_API_KEY}
fi

echo ""
echo -e "${GREEN}Optional Variables:${NC}"
echo ""

# GOOGLE_CLIENT_ID
if [ -z "$GOOGLE_CLIENT_ID" ]; then
    read -p "GOOGLE_CLIENT_ID (optional, for OAuth): " GOOGLE_CLIENT_ID
else
    read -p "GOOGLE_CLIENT_ID [current: $GOOGLE_CLIENT_ID]: " NEW_GOOGLE_CLIENT_ID
    GOOGLE_CLIENT_ID=${NEW_GOOGLE_CLIENT_ID:-$GOOGLE_CLIENT_ID}
fi

# GOOGLE_CLIENT_SECRET
if [ -z "$GOOGLE_CLIENT_SECRET" ]; then
    read -p "GOOGLE_CLIENT_SECRET (optional, for OAuth): " GOOGLE_CLIENT_SECRET
else
    read -p "GOOGLE_CLIENT_SECRET [current: (hidden)] (press Enter to keep, or type new): " NEW_GOOGLE_CLIENT_SECRET
    GOOGLE_CLIENT_SECRET=${NEW_GOOGLE_CLIENT_SECRET:-$GOOGLE_CLIENT_SECRET}
fi

# Set defaults for Flask
FLASK_HOST=${FLASK_HOST:-"127.0.0.1"}
FLASK_PORT=${FLASK_PORT:-"5001"}
FLASK_DEBUG=${FLASK_DEBUG:-"False"}

# Create .env file
echo -e "${GREEN}Creating .env file...${NC}"
cat > "$ENV_FILE" <<EOF
# Hostaway Messages Production Environment Variables
# Generated by setup-env.sh

# Database Configuration
DATABASE_URL=$DATABASE_URL

# Flask Configuration
SECRET_KEY=$SECRET_KEY
FLASK_HOST=$FLASK_HOST
FLASK_PORT=$FLASK_PORT
FLASK_DEBUG=$FLASK_DEBUG

# OpenAI Configuration
OPENAI_API_KEY=$OPENAI_API_KEY

# Hostaway API Configuration (optional, for sync operations)
HOSTAWAY_ACCOUNT_ID=$HOSTAWAY_ACCOUNT_ID
HOSTAWAY_API_KEY=$HOSTAWAY_API_KEY

# Google OAuth Configuration (optional)
GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET

# Sync Configuration
SYNC_FULL_ON_START=False
SYNC_INCREMENTAL_DAILY=True
SYNC_INTERVAL_HOURS=24
VERBOSE=True
BATCH_SIZE=50
EOF

# Set proper permissions
chmod 600 "$ENV_FILE"
chown hostaway:hostaway "$ENV_FILE"

echo ""
echo -e "${GREEN}=========================================${NC}"
echo -e "${GREEN}Environment variables configured!${NC}"
echo -e "${GREEN}=========================================${NC}"
echo ""
echo ".env file created at: $ENV_FILE"
echo "Permissions: 600 (owner read/write only)"
echo ""

