#!/bin/bash
# Helper script to add environment variables to Vercel
# This generates commands you can run to add env vars via Vercel CLI

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_ROOT"

echo "============================================================"
echo "Vercel Environment Variables - CLI Commands"
echo "============================================================"
echo ""
echo "Run these commands to add environment variables to Vercel:"
echo ""
echo "# Database URLs"
echo "vercel env add DATABASE_URL production preview development"
echo "vercel env add USERS_DATABASE_URL production preview development"
echo "vercel env add CACHE_DATABASE_URL production preview development"
echo ""
echo "# AWS S3"
echo "vercel env add AWS_ACCESS_KEY_ID production preview development"
echo "vercel env add AWS_SECRET_ACCESS_KEY production preview development"
echo "vercel env add AWS_S3_BUCKET_NAME production preview development"
echo "vercel env add AWS_S3_REGION production preview development"
echo "vercel env add CONVERSATIONS_S3_PREFIX production preview development"
echo ""
echo "# Flask"
echo "vercel env add SECRET_KEY production preview development"
echo "vercel env add FLASK_DEBUG production preview development"
echo "vercel env add FLASK_HOST production preview development"
echo "vercel env add FLASK_PORT production preview development"
echo ""
echo "# Other"
echo "vercel env add VERBOSE production preview development"
echo "vercel env add MESSAGE_SYNC_PARALLEL_WORKERS production preview development"
echo "vercel env add VERCEL production preview development"
echo ""
echo "============================================================"
echo ""
echo "Or add them via web interface:"
echo "1. Go to https://vercel.com/dashboard"
echo "2. Select your project"
echo "3. Settings → Environment Variables"
echo "4. Add each variable from VERCEL_ENV_VARS.md"
echo ""

